import { atom } from "recoil";
import { lv1NFT } from "../data";

export const nftHistoryState = atom({
  key: "nftHistoryState",
  default: [],
});

export const ownedNFTsState = atom({
  key: "ownedNFTsState",
  default: [],
});

export const allNFTState = atom({
  key: "allNFTState",
  default: [
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
      background: "middle blue",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
      background: "orange",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
    {
      imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
      background: "spring green",
      wing: "elf wings",
      body: "white pearl",
      hat: "blue pointed hat",
      eye: "little blue eyes",
      sdg: "SDG13",
      cot: 8000,
      neutralized: false,
    },
  ],
});
