import collection_b from "./assets/Briquettes.webp";
import collection_c from "./assets/CandyTree.webp";
import collection_f from "./assets/WaterRabbit.webp";
import collection_e from "./assets/PunkChef.webp";
import collection_a from "./assets/Bottle.webp";
import collection_d from "./assets/Hot-potMan.webp";

export const lv1NFT = [
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://B6ta9Jz_Ceiw8EAk63zA_Zjo9Rg1JuGy4EAkPZYqRU8",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://16_IDOSl3tbSs_HLQB7tBz-sUvwlbcqM3dxo6s_BdCA",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
];
export const lv2NFT = [];
export const lv3NFT = [];

export const collections = {
  Bottle: {
    contractAddress: "0x0",
    background: collection_a,
    title: "Greentech Emissions Reductions",
    creator: "Feijie",
    cot: "45,380",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  Briquettes: {
    contractAddress: "0xE813dc876Ce3882543CB6B2F1Cb39A7AEF29C31D",
    background: collection_b,
    title: "Sichuan Biogas Stove Development Programme",
    creator: "Feijie",
    cot: "800,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Candy Tree": {
    contractAddress: "0x00",
    background: collection_c,
    creator: "Feijie",
    title: "Greentech Emissions Reductions",
    cot: "6436.8",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Hot-pot Man": {
    contractAddress: "0x0",
    background: collection_d,
    creator: "Felix",
    title: "Solar Cooking for Refugee Families in Chad",
    cot: "20,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Punk Chef": {
    contractAddress: "0x0",
    background: collection_e,
    creator: "Feijie",
    title: "Improved cookstoves in Maputo city, Mozambique",
    cot: "15,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Water Rabbit": {
    contractAddress: "0x0",
    background: collection_f,
    creator: "Feijie",
    title: "Lango Safe Water Project",
    cot: "10,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
};
