import collection_b from "./assets/Briquettes.webp"
import collection_c from "./assets/CandyTree.webp"
import collection_f from "./assets/WaterRabbit.webp"
import collection_e from "./assets/PunkChef.webp"
import collection_a from "./assets/Bottle.webp"
import collection_d from "./assets/Hot-potMan.webp"

export const initialNFTs = [
  {
    imageUrl: "BAmkwU8BAbFWhy72IsWDPAWorwcmLyO1gNubbmR7akA",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "DWC3zGz0jqas2w1jwPlu2WT_ILwJEhrcMU-3Z23a6FA",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KfsmpwwVcvFlwuoivqg_9XcfxMFHaDVcew2TqxHWWVk",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "9SN5_qYYuMBc1AxSNCvJGFP-Us0lw_8Y5qimT_zuQyQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "8oWfebQwwhgxjvwJu5_5-7SmD4QwmPu1P5LOqe9BLlQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "O-2VNVY9IfPaQXWDCxzNG9UfOrVAxOTXB5RdwALVBDQ",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KbfgJckUFdYoe_rySJCDxmFJ3o7AKasb72B9JuGE8xc",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "BAmkwU8BAbFWhy72IsWDPAWorwcmLyO1gNubbmR7akA",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KbfgJckUFdYoe_rySJCDxmFJ3o7AKasb72B9JuGE8xc",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "J8kDJEjJ5BiZZr1RUxjCitD-TAVBHkG2-PNU_p201TE",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZYzMI3gw85Lz3afT0wZD077m_I5sPahWlJoRnZy-4lg",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IFV62myMJ-k1zhY_ip2nu33u1QzNjF_ZW4wOYeisE9s",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "4j0rQFgxLREiZIrP1PO5BjOmPDHImQBSK_3bn9VnQEo",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "a4_feAr37B_xezE7K1bYOB8I_pDoZlsYIfLheOpFjTs",
    background: "cantaloupe",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6hIPu3ibJZUzjpq_i7Q52DvfcoNc2Ak9RSGheRq4Ndc",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "4j0rQFgxLREiZIrP1PO5BjOmPDHImQBSK_3bn9VnQEo",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "nVbKzMQsjiotg-snst29Icpl3AhvFzVQo2Bj7pWQUpM",
    background: "orange",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "5ndgIiNw-JTsgX9jHHWSOVgziJ7DW68xfTUsNeMTQic",
    background: "spring green",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IXrn0nzheF7TbPxQzBBh6xj6LADQjwWWr5H5lOPCHCo",
    background: "orange",
    wing: "dart wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "PKrtVD5ODr6VDL1R9GR0kvTwUp_FHSjKAALyrXG2e_Y",
    background: "cantaloupe",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "DWC3zGz0jqas2w1jwPlu2WT_ILwJEhrcMU-3Z23a6FA",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZYzMI3gw85Lz3afT0wZD077m_I5sPahWlJoRnZy-4lg",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "9SN5_qYYuMBc1AxSNCvJGFP-Us0lw_8Y5qimT_zuQyQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "liijSSZXPRnqCCASVSrbz9F-BAGk-Fw1AD9N-zdMoWw",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "Zemw1O2PXnLaN3de0Fd4Vo3jJXvzrhd_RFYIHbzVy_4",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "eiCgRmVMcmjNiUyXjIbpXNfCo8EIoo_jYHk4ond0Pek",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6jmFpN39EgVHLDsMZjKvOrJ3XsnuZqK00bLfmQg8qKU",
    background: "spring green",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "CaBJM6_H-_CVK0VRMGq7eDngmTgCk-CcCTQITk9H3-U",
    background: "orange",
    wing: "blue bee wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "middle blue",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "6yCoa2lcNxRlEz5wRwn8vaDyXcgRBtVtQ6kQv9WaJpw",
    background: "spring green",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "middle blue",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "g_RjDYHCR1GpmyTg0PwqENrFkDX3H-4VMcH9rMSxWjU",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "BAmkwU8BAbFWhy72IsWDPAWorwcmLyO1gNubbmR7akA",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g_RjDYHCR1GpmyTg0PwqENrFkDX3H-4VMcH9rMSxWjU",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "9SN5_qYYuMBc1AxSNCvJGFP-Us0lw_8Y5qimT_zuQyQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "es5V6yoV4loXP64JRwt4GCUYERPKPJjTaPxfFOJ-sKI",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "eiCgRmVMcmjNiUyXjIbpXNfCo8EIoo_jYHk4ond0Pek",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g_RjDYHCR1GpmyTg0PwqENrFkDX3H-4VMcH9rMSxWjU",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZYzMI3gw85Lz3afT0wZD077m_I5sPahWlJoRnZy-4lg",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "f9JL9xoRUsg-_Czq3apgICcbcQx0J_TZses5-sm1cJM",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "w1SRYw5uS8cvcMqlhpNoTyoOmIQZwIQZ8HSRJaWbAVE",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "GkXWa3qu_H7UndcAyxKwabbRFHov3bBdKcUlQ4Wp6mg",
    background: "middle blue",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "dmCQsjhaEIuEdjAHqAb-yI36YbmO4CNj0gDlxedBOLY",
    background: "cantaloupe",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IXrn0nzheF7TbPxQzBBh6xj6LADQjwWWr5H5lOPCHCo",
    background: "orange",
    wing: "dart wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "UiDXGw7_TtvnMM6HpKaRQlxfqUrOQDTL1jvgkzS9s2I",
    background: "spring green",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "sS1a3gPyUNzRyg9Mh7pYwzq1Fd8IJVRpDcn7npJ-1Kk",
    background: "middle blue",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "eiCgRmVMcmjNiUyXjIbpXNfCo8EIoo_jYHk4ond0Pek",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "PKrtVD5ODr6VDL1R9GR0kvTwUp_FHSjKAALyrXG2e_Y",
    background: "cantaloupe",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KfsmpwwVcvFlwuoivqg_9XcfxMFHaDVcew2TqxHWWVk",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "5ndgIiNw-JTsgX9jHHWSOVgziJ7DW68xfTUsNeMTQic",
    background: "spring green",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "a4_feAr37B_xezE7K1bYOB8I_pDoZlsYIfLheOpFjTs",
    background: "cantaloupe",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "Zemw1O2PXnLaN3de0Fd4Vo3jJXvzrhd_RFYIHbzVy_4",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "2g7m6AyYmQqk6onT18TjsxTQyiGWzShwCG-XfiMMzx0",
    background: "orange",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZYzMI3gw85Lz3afT0wZD077m_I5sPahWlJoRnZy-4lg",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "dmCQsjhaEIuEdjAHqAb-yI36YbmO4CNj0gDlxedBOLY",
    background: "cantaloupe",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "GkXWa3qu_H7UndcAyxKwabbRFHov3bBdKcUlQ4Wp6mg",
    background: "middle blue",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "4j0rQFgxLREiZIrP1PO5BjOmPDHImQBSK_3bn9VnQEo",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6jmFpN39EgVHLDsMZjKvOrJ3XsnuZqK00bLfmQg8qKU",
    background: "spring green",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "J8kDJEjJ5BiZZr1RUxjCitD-TAVBHkG2-PNU_p201TE",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "O-2VNVY9IfPaQXWDCxzNG9UfOrVAxOTXB5RdwALVBDQ",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "es5V6yoV4loXP64JRwt4GCUYERPKPJjTaPxfFOJ-sKI",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IFV62myMJ-k1zhY_ip2nu33u1QzNjF_ZW4wOYeisE9s",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "XfQXpJ51WNkm0Ff6MqlwUa3Aqa7VkgHaehtKkFtAkQI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "a4_feAr37B_xezE7K1bYOB8I_pDoZlsYIfLheOpFjTs",
    background: "cantaloupe",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IFV62myMJ-k1zhY_ip2nu33u1QzNjF_ZW4wOYeisE9s",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g6kCj5HA24nbz5Grj1Zcn7LJvk44r0vxjS26sB_j66w",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "jM3Vmnk5WwVq3-9-nx-oVajn6C7xjpeW1bDJzfV30KI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "sS1a3gPyUNzRyg9Mh7pYwzq1Fd8IJVRpDcn7npJ-1Kk",
    background: "middle blue",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6hIPu3ibJZUzjpq_i7Q52DvfcoNc2Ak9RSGheRq4Ndc",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "DWC3zGz0jqas2w1jwPlu2WT_ILwJEhrcMU-3Z23a6FA",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g_RjDYHCR1GpmyTg0PwqENrFkDX3H-4VMcH9rMSxWjU",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "PKrtVD5ODr6VDL1R9GR0kvTwUp_FHSjKAALyrXG2e_Y",
    background: "cantaloupe",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "liijSSZXPRnqCCASVSrbz9F-BAGk-Fw1AD9N-zdMoWw",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "8oWfebQwwhgxjvwJu5_5-7SmD4QwmPu1P5LOqe9BLlQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "J8kDJEjJ5BiZZr1RUxjCitD-TAVBHkG2-PNU_p201TE",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "7QvZXG-fpkb-qklcTZQqi1oBD3OFPMkF74042RQCtvs",
    background: "spring green",
    wing: "dart wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "JFdwZSNHQ2QsrZ1gF9e-LZSlIMkXj0YmXR2UeQ-T6jk",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IXrn0nzheF7TbPxQzBBh6xj6LADQjwWWr5H5lOPCHCo",
    background: "orange",
    wing: "dart wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "sS1a3gPyUNzRyg9Mh7pYwzq1Fd8IJVRpDcn7npJ-1Kk",
    background: "middle blue",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "sAIahCvKBqis_9GM1ovhfuWxltbL0EuJQos0B64qYks",
    background: "middle blue",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "XfQXpJ51WNkm0Ff6MqlwUa3Aqa7VkgHaehtKkFtAkQI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "UiDXGw7_TtvnMM6HpKaRQlxfqUrOQDTL1jvgkzS9s2I",
    background: "spring green",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KbfgJckUFdYoe_rySJCDxmFJ3o7AKasb72B9JuGE8xc",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "dmCQsjhaEIuEdjAHqAb-yI36YbmO4CNj0gDlxedBOLY",
    background: "cantaloupe",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "O-2VNVY9IfPaQXWDCxzNG9UfOrVAxOTXB5RdwALVBDQ",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
]

export const lv1NFT = [
  {
    imageUrl: "XfQXpJ51WNkm0Ff6MqlwUa3Aqa7VkgHaehtKkFtAkQI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "w1SRYw5uS8cvcMqlhpNoTyoOmIQZwIQZ8HSRJaWbAVE",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g_RjDYHCR1GpmyTg0PwqENrFkDX3H-4VMcH9rMSxWjU",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "sAIahCvKBqis_9GM1ovhfuWxltbL0EuJQos0B64qYks",
    background: "middle blue",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "9SjSmYPw6d4CJD8jBo0_cLqip6npAjvIdBiX55yDqik",
    background: "orange",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "8oWfebQwwhgxjvwJu5_5-7SmD4QwmPu1P5LOqe9BLlQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "4j0rQFgxLREiZIrP1PO5BjOmPDHImQBSK_3bn9VnQEo",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KfsmpwwVcvFlwuoivqg_9XcfxMFHaDVcew2TqxHWWVk",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "5ndgIiNw-JTsgX9jHHWSOVgziJ7DW68xfTUsNeMTQic",
    background: "spring green",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "eiCgRmVMcmjNiUyXjIbpXNfCo8EIoo_jYHk4ond0Pek",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6hIPu3ibJZUzjpq_i7Q52DvfcoNc2Ak9RSGheRq4Ndc",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZYzMI3gw85Lz3afT0wZD077m_I5sPahWlJoRnZy-4lg",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "gG37TJAaKmvjs0ue030arzM8E4B1rKPDR0YCYpRRPgU",
    background: "orange",
    wing: "blue bee wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "DWC3zGz0jqas2w1jwPlu2WT_ILwJEhrcMU-3Z23a6FA",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "utVQbGVTiG-ZAFmBNJPthZxFgnWrO29zfLBCxOWjURI",
    background: "orange",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "middle blue",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "G14gmzWliT5B_7crhywT1Y-qgfNvwPXuanXH_kiEUGc",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "2g7m6AyYmQqk6onT18TjsxTQyiGWzShwCG-XfiMMzx0",
    background: "orange",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "BAmkwU8BAbFWhy72IsWDPAWorwcmLyO1gNubbmR7akA",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "red pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6yCoa2lcNxRlEz5wRwn8vaDyXcgRBtVtQ6kQv9WaJpw",
    background: "spring green",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "IXrn0nzheF7TbPxQzBBh6xj6LADQjwWWr5H5lOPCHCo",
    background: "orange",
    wing: "dart wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "044SUiCeUGBWZuT-gM62r2U6StGrZj54UOofUSJHk9w",
    background: "middle blue",
    wing: "elf wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "es5V6yoV4loXP64JRwt4GCUYERPKPJjTaPxfFOJ-sKI",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "GkXWa3qu_H7UndcAyxKwabbRFHov3bBdKcUlQ4Wp6mg",
    background: "middle blue",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "KbfgJckUFdYoe_rySJCDxmFJ3o7AKasb72B9JuGE8xc",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "J8kDJEjJ5BiZZr1RUxjCitD-TAVBHkG2-PNU_p201TE",
    background: "spring green",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "UiDXGw7_TtvnMM6HpKaRQlxfqUrOQDTL1jvgkzS9s2I",
    background: "spring green",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "JFdwZSNHQ2QsrZ1gF9e-LZSlIMkXj0YmXR2UeQ-T6jk",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "7QvZXG-fpkb-qklcTZQqi1oBD3OFPMkF74042RQCtvs",
    background: "spring green",
    wing: "dart wings",
    body: "blue pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "dmCQsjhaEIuEdjAHqAb-yI36YbmO4CNj0gDlxedBOLY",
    background: "cantaloupe",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "9SN5_qYYuMBc1AxSNCvJGFP-Us0lw_8Y5qimT_zuQyQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "nVbKzMQsjiotg-snst29Icpl3AhvFzVQo2Bj7pWQUpM",
    background: "orange",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "a4_feAr37B_xezE7K1bYOB8I_pDoZlsYIfLheOpFjTs",
    background: "cantaloupe",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "red pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "KyDKRIxEpClKHTict6yYlUW8-YOodgvvG5yDenMhP4M",
    background: "orange",
    wing: "dart wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "Zemw1O2PXnLaN3de0Fd4Vo3jJXvzrhd_RFYIHbzVy_4",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "IFV62myMJ-k1zhY_ip2nu33u1QzNjF_ZW4wOYeisE9s",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6jmFpN39EgVHLDsMZjKvOrJ3XsnuZqK00bLfmQg8qKU",
    background: "spring green",
    wing: "blue bee wings",
    body: "purple pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "jM3Vmnk5WwVq3-9-nx-oVajn6C7xjpeW1bDJzfV30KI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "DSwmDecoYlp_N6avu_gGgktFwQXrxjdwiT1VnZMEp0k",
    background: "spring green",
    wing: "blue bee wings",
    body: "red pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "PKrtVD5ODr6VDL1R9GR0kvTwUp_FHSjKAALyrXG2e_Y",
    background: "cantaloupe",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "eiDr8_M0Jm-VHW756MrH6ZwBbuaxNu2pFmhu5pakM0k",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "bee tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "g6kCj5HA24nbz5Grj1Zcn7LJvk44r0vxjS26sB_j66w",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "snail tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "xkQk1G0AUIbKN3D1_Ms43BoG-y7j5yGmsk-hi2zG3eU",
    background: "orange",
    wing: "elf wings",
    body: "yellow pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "OZrL9rmdKdpwrbDqe8vTTB-ukSjo7Hmkh4h0Cf7L1xg",
    background: "spring green",
    wing: "blue bee wings",
    body: "white pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "O-2VNVY9IfPaQXWDCxzNG9UfOrVAxOTXB5RdwALVBDQ",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "sS1a3gPyUNzRyg9Mh7pYwzq1Fd8IJVRpDcn7npJ-1Kk",
    background: "middle blue",
    wing: "elf wings",
    body: "black pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "CaBJM6_H-_CVK0VRMGq7eDngmTgCk-CcCTQITk9H3-U",
    background: "orange",
    wing: "blue bee wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "liijSSZXPRnqCCASVSrbz9F-BAGk-Fw1AD9N-zdMoWw",
    background: "orange",
    wing: "elf wings",
    body: "red pearl",
    hat: "snail tentacles",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "f9JL9xoRUsg-_Czq3apgICcbcQx0J_TZses5-sm1cJM",
    background: "spring green",
    wing: "elf wings",
    body: "black pearl",
    hat: "bee tentacles",
    eye: "villain machine",
    sdg: "SDG13",
  },
  {
    imageUrl: "uSrrqAx36_9vPXtTWx9O5-R1_Zod_DSaF-r-SN-NGAM",
    background: "spring green",
    wing: "elf wings",
    body: "blue pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "r0djV8JLfBeSXVpIoYdpL1KbFfWGX5Xwg5UuZwzmc08",
    background: "cantaloupe",
    wing: "elf wings",
    body: "red pearl",
    hat: "bee tentacles",
    eye: "little white eyes",
    sdg: "SDG13",
  },
]
export const lv2NFT = [
  {
    imageUrl: "sa-q45P56CzUYv3Qe7hmFn4hcBSFO0Mxdm3ODZ0PBwY",
    background: "copper wire",
    wing: "mechanical plastic wings",
    body: "blue algae",
    hat: "white chef cap",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "hzL37P_9vCyBbT-Lpmst-uIZHLyfpMKS5fBLgUy-e8I",
    background: "nickel grid",
    wing: "green algae wings",
    body: "white velvet elf",
    hat: "golden chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "fwo7yB9G-CtTq_pUddf_LT3BHGGYY2NdkM_uW4O_BSM",
    background: "nickel grid",
    wing: "bat wings",
    body: "white velvet elf",
    hat: "white chef cap",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "#NAME?",
    background: "leather",
    wing: "bat wings",
    body: "blue algae",
    hat: "golden chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "xzl4kz762EgtS4FQhc6t2oU4zBD9T2Oh-gVOMfPIQNM",
    background: "nickel grid",
    wing: "green algae wings",
    body: "gren algae weaving",
    hat: "golden chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "Pp9Z6hU1qQuYrN4crnKtVHtchY4ytYtj2sjt1QFYxbQ",
    background: "copper grid",
    wing: "green algae wings",
    body: "white velvet elf",
    hat: "white chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "HrZVh3JPfMAGBULCuR8hPjcdJjWl5YV5NGcKwF_otno",
    background: "copper grid",
    wing: "mechanical plastic wings",
    body: "gren algae weaving",
    hat: "white chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "Tt90uFOWog8f5t6UVeae2YHSI9Aemzc2iQUisTKjNB8",
    background: "copper grid",
    wing: "mechanical plastic wings",
    body: "blue algae",
    hat: "white chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "deAPI7CXH41EeIK2KXBaE-c1R86kF0bXxVd0Bgy5yTM",
    background: "leather",
    wing: "green algae wings",
    body: "white velvet elf",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "gaeE_KJJ1BbwlspHk8DDcs0LkXzbSn3Vno8Keq3E6xw",
    background: "copper wire",
    wing: "hydrilla wings",
    body: "blue algae",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "ZERwRW2Qsqr3aYhCdBpl8Jg3PfBhdlDFTX8Ox2TFzVE",
    background: "nickel grid",
    wing: "mechanical plastic wings",
    body: "white velvet elf",
    hat: "golden chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "q7MqPrvX0mu2ydGwCPzh92YftcCKjCbfz2G40HLZVpw",
    background: "copper grid",
    wing: "bat wings",
    body: "blue algae",
    hat: "golden chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "iXWme1cqTgEMN5n4G3KgnaIMD7IgFKLLYZzbRLLn5Ec",
    background: "copper grid",
    wing: "hydrilla wings",
    body: "gren algae weaving",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "mHNroKmuyqad_4U3BwiDCtiloai4ejHgWNj9YeQxqXw",
    background: "copper wire",
    wing: "bat wings",
    body: "gren algae weaving",
    hat: "golden chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "mHNroKmuyqad_4U3BwiDCtiloai4ejHgWNj9YeQxqXw",
    background: "nickel grid",
    wing: "green algae wings",
    body: "gren algae weaving",
    hat: "white chef cap",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "H3tOWhBpFbo_zISEU3Dlxgf-6UCPl4FBguEUrYzQabc",
    background: "nickel grid",
    wing: "bat wings",
    body: "white velvet elf",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "NMCO1AT1qnfamLk6fpM_gCq2Goa9blfbKn5a9bXAUKc",
    background: "leather",
    wing: "bat wings",
    body: "balck leather",
    hat: "golden chef cap",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "_7FgsGAyaeliqKPghD08Z67319z-tIAb17nKNf4W7xA",
    background: "copper wire",
    wing: "green algae wings",
    body: "white velvet elf",
    hat: "golden chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "JJqO8tGXOCYIYDft0IrxqqeA0YWKEJVQ9QoiVmEaGQQ",
    background: "leather",
    wing: "bat wings",
    body: "balck leather",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "G256my2qMW8Hr4hLo-ooanIR4VG57loRveRTKfelCjg",
    background: "nickel grid",
    wing: "bat wings",
    body: "white velvet elf",
    hat: "golden chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "X7XrdYOSEOWHDYfiBLOPO_qZNyMqQlT1U8jQcfqDTV0",
    background: "copper grid",
    wing: "hydrilla wings",
    body: "blue algae weaving",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "6pOcRCdKMbh81QzTzrs3G5-LHps_9GbPdEMS1VF4b94",
    background: "leather",
    wing: "bat wings",
    body: "blue algae",
    hat: "white chef cap",
    eye: "little blue eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "ux5O7ugViMuqHIK61YLOR3Pyu54dbxEdKzJguN4_8mU",
    background: "nickel grid",
    wing: "hydrilla wings",
    body: "balck leather",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
  {
    imageUrl: "fWQjicjyu8Vganeu61J0Tw92JaydCMNsVgpN8K8uKPM",
    background: "nickel grid",
    wing: "mechanical plastic wings",
    body: "gren algae weaving",
    hat: "white chef cap",
    eye: "motorcycle glasses",
    sdg: "SDG13",
  },
  {
    imageUrl: "CP2JpObOnwMEP1mGF3Vx2slc8MccueakttUcg3aMjrQ",
    background: "copper wire",
    wing: "mechanical plastic wings",
    body: "gren algae weaving",
    hat: "white chef cap",
    eye: "little white eyes",
    sdg: "SDG13",
  },
]
export const lv3NFT = [
  {
    imageUrl: "Yy4WWruzKmQfPQWuU5mUqTVK9zpUz1v9m__9o0gYYMA",
    background: "anodized alumina rough purple",
    wing: "light goddess wings",
    body: "red dark demon",
    hat: "golden chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "mH77AtkKLNYJ8Csm2PuM5Hbab5eL9azi1EUHf2JFYBQ",
    background: "peaceful arming",
    wing: "light goddess wings",
    body: "steel weaving",
    hat: "white chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "2D2Fjn8Cq7x0sq9GiAyPOkrMHnnjlFnUIZwmujZvCaA",
    background: "drunk",
    wing: "mechanical fight angle",
    body: "dark blast",
    hat: "golden chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "kNTpHBm_rqpt875T7LWMniEqiopbOeL40ZpzUowB4J0",
    background: "peaceful arming",
    wing: "light goddess wings",
    body: "dark blast",
    hat: "white chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "0FLS9MNcbi-dw1mbJlWwWshiR64VMlIma7cfmzzHlU0",
    background: "drunk",
    wing: "light goddess wings",
    body: "red dark demon",
    hat: "golden chef cap",
    eye: "winter cool",
    sdg: "SDG13",
  },
  {
    imageUrl: "s9Se59FYejVzFuyxP1FA3HCHLIlzuFR5En5vuoc3MII",
    background: "anodized alumina rough purple",
    wing: "mechanical fight angle",
    body: "steel weaving",
    hat: "golden chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "5tvlGz31UhKT1l8D-lKvdgLgaUd0R0NNOPIifbgkCkg",
    background: "drunk",
    wing: "mechanical fight angle",
    body: "steel weaving",
    hat: "police cap",
    eye: "sky knight",
    sdg: "SDG13",
  },
  {
    imageUrl: "pfla--8uSYJJCrPsRc3SI8rjXBbghXSqIux-EyexNKM",
    background: "brushed obsidian carving",
    wing: "mechanical fight angle",
    body: "dark blast",
    hat: "white chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "BtOIEaT4TDeAukDsHyaRRTtHaiXDzy8B4TbJ88XWvGo",
    background: "drunk",
    wing: "mechanical fight angle",
    body: "red dark demon",
    hat: "white chef cap",
    eye: "winter cool",
    sdg: "SDG13",
  },
  {
    imageUrl: "5s1REVHJjc6jKwJpbxsalj2Ap6eTjHKUdnNHJ1WE6Ac",
    background: "drunk",
    wing: "mechanical fight angle",
    body: "steel weaving",
    hat: "golden chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
  {
    imageUrl: "wT2C34uZ90-0S-YfCOfK7-oXgxCw_N6v5g3zV9zyNog",
    background: "anodized alumina rough purple",
    wing: "light goddess wings",
    body: "dark blast",
    hat: "golden chef cap",
    eye: "punk killer",
    sdg: "SDG13",
  },
]

export const collections = {
  Bottle: {
    contractAddress: "0x0",
    background: collection_a,
    title: "Greentech Emissions Reductions",
    creator: "Feijie",
    cot: "45,380",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  Briquettes: {
    contractAddress: "0x6282593203f769A6ABF81276DbFDF3b1976ac1E7",
    background: collection_b,
    title: "Sichuan Biogas Stove Development Programme",
    creator: "Feijie",
    cot: "800,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Candy Tree": {
    contractAddress: "0x00",
    background: collection_c,
    creator: "Feijie",
    title: "Greentech Emissions Reductions",
    cot: "6436.8",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Hot-pot Man": {
    contractAddress: "0x0",
    background: collection_d,
    creator: "Felix",
    title: "Solar Cooking for Refugee Families in Chad",
    cot: "20,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Punk Chef": {
    contractAddress: "0x0",
    background: collection_e,
    creator: "Feijie",
    title: "Improved cookstoves in Maputo city, Mozambique",
    cot: "15,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Water Rabbit": {
    contractAddress: "0x0",
    background: collection_f,
    creator: "Feijie",
    title: "Lango Safe Water Project",
    cot: "10,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
}
