import collection_b from "./assets/Briquettes.webp";
import collection_c from "./assets/CandyTree.webp";
import collection_f from "./assets/WaterRabbit.webp";
import collection_e from "./assets/PunkChef.webp";
import collection_a from "./assets/Bottle.webp";
import collection_d from "./assets/Hot-potMan.webp";

export const initialNFTs = [
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
];

export const lv1NFT = [
  {
    imageUrl: "ar://oX77wDfZ98CE9DLdl-QLaZAHiwl2lu0T4kQSbr6UFdI",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://18eeAmTV8VFa1flOJPd1JukUssmF_v88odcVpvQw-sg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Chel8AbttrDc5OdoZEbZwKEv5UPpBQgFvAwjnwglGDA",
    background: "middle blue",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://qKXIP_r7X-v9378ZKiZ3-9BuVK829lJX3Rm1gbQfwUg",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Ohz0a6T6aiW0u2P4uGhvENuM9Kc0nvJZYt3UYOGrstA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wwl0PgdubXgN_0qOFVmGJhTMKdU40Y2E3jhmTUpW8gs",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://X2nCbktx9hVILcmkWi0Wrep45i912bmDxA8hWSuRnI4",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://YAP3qRo8mTAtcB6h_h_oV6caTL1SdJQMAtzks5Dpf1M",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fpRGhOIJAa_8ZZ2YxGDyaRWM0HL-xj_3KCATXtj_Rbs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://B6ta9Jz_Ceiw8EAk63zA_Zjo9Rg1JuGy4EAkPZYqRU8",
    background: "orange",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://16_IDOSl3tbSs_HLQB7tBz-sUvwlbcqM3dxo6s_BdCA",
    background: "cantaloupe",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
];
export const lv2NFT = [
  {
    imageUrl: "ar://6DkJlZnQyRo-1BREZhljVvJhWC-n64C8MoBb4M3kMMk",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://ZNPmBszbYIKzEJhrUfKaz2x5AM-XAMZZEOpBzDcccmU",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://dEjZa5Nvdxuw9p0B72DGcCKxVD1B5fBXms0wdWKyWfs",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://Pl1NEH40R4dV38SE_D41rD5NnEUzRC-1lRpVWRgXxAE",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://bs9L7-WcOsTyM7VlRpDDCCR1KQJ9gj3ePlMp5NViuN0",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fwhquuouVSoa1mvAFMafmwW45xS6E1nSLCgRlmwTp_E",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://TzIA8_o3LUoVGeq3YiDcTI2gYOnGJgP0hodT8LqifG0",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://udYaSJ3vIEbGTg6VMjrHVMfOL3JsxkUuHfIemau5cns",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://zAFNqZ6-YiuCoMXevO_G3w2Ph6WNILBfFyxwdgdeoUU",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://ihaKF5XpbtbEutfu2tkDWUBNz4DpwO2xBasbkcn5i2c",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://fkCSZE-MROXnyimpk7L6pkIoM9aZ8v1bY05ZUqrEBvA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
];
export const lv3NFT = [
  {
    imageUrl: "ar://Yy4WWruzKmQfPQWuU5mUqTVK9zpUz1v9m__9o0gYYMA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://mH77AtkKLNYJ8Csm2PuM5Hbab5eL9azi1EUHf2JFYBQ",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://2D2Fjn8Cq7x0sq9GiAyPOkrMHnnjlFnUIZwmujZvCaA",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://kNTpHBm_rqpt875T7LWMniEqiopbOeL40ZpzUowB4J0",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://0FLS9MNcbi-dw1mbJlWwWshiR64VMlIma7cfmzzHlU0",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://s9Se59FYejVzFuyxP1FA3HCHLIlzuFR5En5vuoc3MII",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://5tvlGz31UhKT1l8D-lKvdgLgaUd0R0NNOPIifbgkCkg",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://pfla--8uSYJJCrPsRc3SI8rjXBbghXSqIux-EyexNKM",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://BtOIEaT4TDeAukDsHyaRRTtHaiXDzy8B4TbJ88XWvGo",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://5s1REVHJjc6jKwJpbxsalj2Ap6eTjHKUdnNHJ1WE6Ac",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
  {
    imageUrl: "ar://wT2C34uZ90-0S-YfCOfK7-oXgxCw_N6v5g3zV9zyNog",
    background: "spring green",
    wing: "elf wings",
    body: "white pearl",
    hat: "blue pointed hat",
    eye: "little blue eyes",
    sdg: "SDG13",
    cot: 8000,
    neutralized: false,
  },
];

export const collections = {
  Bottle: {
    contractAddress: "0x0",
    background: collection_a,
    title: "Greentech Emissions Reductions",
    creator: "Feijie",
    cot: "45,380",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  Briquettes: {
    contractAddress: "0x6ee0649Bbd94250AFDAD81E967019EF2efAaF0d5",
    background: collection_b,
    title: "Sichuan Biogas Stove Development Programme",
    creator: "Feijie",
    cot: "800,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Candy Tree": {
    contractAddress: "0x00",
    background: collection_c,
    creator: "Feijie",
    title: "Greentech Emissions Reductions",
    cot: "6436.8",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Hot-pot Man": {
    contractAddress: "0x0",
    background: collection_d,
    creator: "Felix",
    title: "Solar Cooking for Refugee Families in Chad",
    cot: "20,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Punk Chef": {
    contractAddress: "0x0",
    background: collection_e,
    creator: "Feijie",
    title: "Improved cookstoves in Maputo city, Mozambique",
    cot: "15,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
  "Water Rabbit": {
    contractAddress: "0x0",
    background: collection_f,
    creator: "Feijie",
    title: "Lango Safe Water Project",
    cot: "10,000",
    location: "Sichuan, China",
    registry: "Gold Standard",
    methology: "COM PoA 2898GS 1239",
  },
};
